name: ccc
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - black
  - flake8
  - pre-commit
  - pytest
  - pytest-cov
  - pip
  - python-dotenv
  - eventlet==0.30.2
  - gunicorn
  - bcrypt
  - elasticsearch=7.13.3
  - pyyaml
  - pip:
    - Flask
    - flask-socketio
    - Flask-Login
    - redis
    - beautifulsoup4
    - lxml
    - async-timeout >=4.0.0a3,<5.0
